//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public override string ToString()
        {
            if (Id == 0) return Фреймворки;
            else if (Id == 1) return ЯзыкиПрограммирования;
            else return Библиотеки;
        }
        public int Id { get; set; }
        public string Фреймворки { get; set; }
        public string ЯзыкиПрограммирования { get; set; }
        public string Библиотеки { get; set; }
        public int UsersSetId { get; set; }
    
        public virtual UsersSet UsersSet { get; set; }
    }
}
